### ISSUE TITLE
Zattoo HiQ EPG not shown

### ISSUE THREAD

**Issue by elijahbailey** [rolapp/plugin.video.zattooHiQ#17]
zattoo HiQ 1.3.8 (31.12.2017) on Kodi 17.6 (OSMC) raspberry Pi
installed from rolapp/plugin.video.zattooHiQ.zip

Issue: the EPG does not load - payed zattoo account, location Germany

If you need log information please let me do which is needed.

if installed from superreops I receive an MD5 checksum error.

**Comment by rolapp** [comment]
The update is in the kodinerdstepo
v1.4.0



Am 13. Februar 2018 17:31:22 schrieb elijahbailey <notifications@github.com>:

**Comment by elijahbailey** [comment]
great, thanks
